spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521/ORCL
    username: LOCALTESTER
    password: LOCALTESTER
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    properties:
      hibernate:
         show_sql: true
         format_sql: true
         use_sql_comments: true
  thymeleaf:
    cache: false
    resources:
      cache-period: 0
logging:
  level:
#    root: info
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
#    com.SystemMail.mail: debug
mail:
  domain: saramnuri.com
  propertyMap:
    returnPath: jwpark@saramnuri.com
    X-Mailer: mailer
    MIME-Version: 1.0
    DKIM-Signature: test


domain:
  domainConnectionInfo:
    naver.com: 10
    nate.com: 10
    daum.net: 6
    default: 15

